VERILOG ?= PS2Test.v

prog: bin/toplevel.bit
	ujprog $<

IDCODE ?= 0x41113043 # 85f

bin/toplevel.json: ${VERILOG}
	mkdir -p bin
	yosys \
		-p "synth_ecp5 -abc9 -json $@" \
		${VERILOG} 

bin/toplevel.config: bin/toplevel.json
	nextpnr-ecp5 \
		--json $< \
		--textcfg $@ \
		--lpf ulx3s_ps2.lpf \
		--85k \
		--package CABGA381

bin/toplevel.bit: bin/toplevel.config
	ecppack --compress --idcode $(IDCODE) $< $@

clean:
	$(RM) -rf bin
